---
hosts:
  host1:
    host: 1.2.3.4
    port: 5432
    user: pgroute66
    b64password: cGEkJHcwcmQ=
  host2:
    host: 1.2.3.5
    port: 5432
    user: pgroute66
    b64password: cGEkJHcwcmQ=
  host3:
    host: 1.2.3.6
    port: 5432
    user: pgroute66
    b64password: cGEkJHcwcmQ=

bind: 127.0.0.1
port: 8080

ssl:
  cert: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dn
  key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQXNZQ0NRRGZYZkhoanBCZHNEQU5CZ2txaGtpRzl

loglevel: debug
verbosity: 9
