---
hosts:
  host1:
    host: pgroute66_postgres_1
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
  host2:
    host: pgroute66_postgres_2
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
  host3:
    host: pgroute66_postgres_3
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=

bind: 0.0.0.0
port: 8080

ssl:
  cert: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dn
  key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQXNZQ0NRRGZYZkhoanBCZHNEQU5CZ2txaGtpRzl

loglevel: debug
verbosity: 9
