---
hosts:
  host1:
    host: pgroute66_postgres_1
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
    application_name: pgroute66
    pool_max_conns: 2
    pool_max_conn_idle_time: 60s
  host2:
    host: pgroute66_postgres_2
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
    application_name: pgroute66
    pool_max_conns: 2
    pool_max_conn_idle_time: 60s
  host3:
    host: pgroute66_postgres_3
    port: 5432
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
    application_name: pgroute66
    pool_max_conns: 2
    pool_max_conn_idle_time: 60s

loglevel: debug

bind: 0.0.0.0

#port: 8443
#ssl:
#  b64cert: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dn
#  b64key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQXNZQ0NRRGZYZkhoanBCZHNEQU5CZ2txaGtpRzl

