---
hosts:
  host1:
    host: 127.0.0.1
    port: 52038
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
  host2:
    host: 127.0.0.1
    port: 60814
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=
  host3:
    host: 127.0.0.1
    port: 60816
    user: postgres
    dbname: postgres
    b64password: cGFzc3dvcmQ=

bind: 127.0.0.1
port: 8080

ssl:
  cert: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dn
  key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQXNZQ0NRRGZYZkhoanBCZHNEQU5CZ2txaGtpRzl

loglevel: debug
verbosity: 9
