version: '3.9'
services:
  pgroute66:
    build: .
    ports:
    - "8080:8080"
    - "8443:8443"
    command:
    - pgroute66
    - "-c"
    - "/test/config.yaml"
    volumes:
    -  ./test:/test
  postgres:
    build: ./docker/postgres
    environment:
    - PGPASSWORD=password
    - PGHOSTS=pgroute66-postgres-1,pgroute66-postgres-2,pgroute66-postgres-3
    ports:
    - "5432"
