version: '3.9'
services:
  postgres:
    build: ./docker/postgres
    environment:
    - PGPASSWORD=password
    - PGHOSTS=pgroute66_postgres_1,pgroute66_postgres_3,pgroute66_postgres_3
    networks:
      postgres: {}
    ports:
    - "5432"
networks:
  postgres:
    driver: bridge
    ipam:
      driver: default
