version: '3.9'
services:
  pgroute66:
    build: .
    ports:
    - "8080:8080"
    - "8443:8443"
    command:
    - pgroute66
    - "-c"
    - "/test/config.yaml"
    volumes:
    -  ./test:/test
  postgres:
    build: ./docker/postgres
    environment:
    - PGPASSWORD=password
    - PGHOSTS=pgroute66_postgres_1,pgroute66_postgres_3,pgroute66_postgres_3
    ports:
    - "5432"
